--liquibase formatted sql

--changeset lsaric:create-users-table
CREATE TABLE users (
    id_user BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(15) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    username VARCHAR(16) NOT NULL UNIQUE,
    avatar_url VARCHAR(255) NOT NULL,
    avatar_public_id VARCHAR(255),
    bio VARCHAR(500),
    is_private BOOL NOT NULL DEFAULT TRUE,
    email VARCHAR(255) UNIQUE,
    password VARCHAR(60) NOT NULL,
    tstamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

--changeset lsaric:create-oauth-accounts-table
CREATE TABLE oauth_account (
    id_oauth_account BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider VARCHAR(20) NOT NULL,
    provider_user_id VARCHAR(255) NOT NULL,
    access_token TEXT,
    refresh_token TEXT,
    CONSTRAINT fk_oauth_user FOREIGN KEY (user_id)
        REFERENCES users(id_user) ON DELETE CASCADE,
    CONSTRAINT uq_provider_user UNIQUE (provider, provider_user_id)
);


CREATE TABLE email_change_request (
    id_request BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    new_email VARCHAR(255) NOT NULL,
    verification_code VARCHAR(10) NOT NULL,
    expiration_time TIMESTAMP NOT NULL,
    CONSTRAINT fk_email_change_request_user
        FOREIGN KEY (user_id) REFERENCES users(id_user) ON DELETE CASCADE
);

CREATE TABLE follow_request (
    id_request BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id BIGINT NOT NULL,
    receiver_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
        CONSTRAINT uq_follow_request UNIQUE (sender_id, receiver_id),
        CONSTRAINT fk_follow_request_sender
            FOREIGN KEY (sender_id) REFERENCES users(id_user) ON DELETE CASCADE,
        CONSTRAINT fk_follow_request_receiver
            FOREIGN KEY (receiver_id) REFERENCES users(id_user) ON DELETE CASCADE
);

CREATE TABLE follows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user1_id BIGINT NOT NULL,
    user2_id BIGINT NOT NULL,
        CONSTRAINT uq_follower UNIQUE (user1_id, user2_id),
        CONSTRAINT fk_follower_1
            FOREIGN KEY (user1_id) REFERENCES users(id_user) ON DELETE CASCADE,
        CONSTRAINT fk_follower2
            FOREIGN KEY (user2_id) REFERENCES users(id_user) ON DELETE CASCADE
);

--changeset lsaric:create-roles-endpoints-tables
CREATE TABLE roles (
    id_role BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(255),
    CONSTRAINT uq_role_name UNIQUE (name)
);

CREATE TABLE endpoints (
    id_endpoint BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    http_method VARCHAR(10) NOT NULL,
    path VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    CONSTRAINT uq_endpoint_method_path UNIQUE (http_method, path)
);

CREATE TABLE role_endpoint (
    id_role_endpoint BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL,
    endpoint_id BIGINT NOT NULL,
    CONSTRAINT uq_role_endpoint UNIQUE (role_id, endpoint_id),
    CONSTRAINT fk_role_endpoint_role
        FOREIGN KEY (role_id) REFERENCES roles(id_role) ON DELETE CASCADE,
    CONSTRAINT fk_role_endpoint_endpoint
        FOREIGN KEY (endpoint_id) REFERENCES endpoints(id_endpoint) ON DELETE CASCADE
);

--changeset lsaric:create-user-role-table
CREATE TABLE user_role (
    id_user_role BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    CONSTRAINT uq_user_role UNIQUE (user_id, role_id),
    CONSTRAINT fk_user_role_user
        FOREIGN KEY (user_id) REFERENCES users(id_user) ON DELETE CASCADE,
    CONSTRAINT fk_user_role_role
        FOREIGN KEY (role_id) REFERENCES roles(id_role) ON DELETE CASCADE
);



