--liquibase formatted sql

--changeset lsaric:create-users-table
CREATE TABLE users (
    id_user BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(15) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    username VARCHAR(16) NOT NULL UNIQUE,
    avatar_url VARCHAR(255) NOT NULL,
    avatar_public_id VARCHAR(255),
    bio VARCHAR(500),
    is_private BOOL NOT NULL DEFAULT TRUE,
    email VARCHAR(255) UNIQUE,
    password VARCHAR(60) NOT NULL,
    tstamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

--changeset lsaric:create-oauth-accounts-table
CREATE TABLE oauth_account (
    id_oauth_account BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider VARCHAR(20) NOT NULL,
    provider_user_id VARCHAR(255) NOT NULL,
    access_token TEXT,
    refresh_token TEXT,
    CONSTRAINT fk_oauth_user FOREIGN KEY (user_id)
        REFERENCES users(id_user) ON DELETE CASCADE,
    CONSTRAINT uq_provider_user UNIQUE (provider, provider_user_id)
);


CREATE TABLE email_change_request (
    id_request BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    new_email VARCHAR(255) NOT NULL,
    verification_code VARCHAR(10) NOT NULL,
    expiration_time TIMESTAMP NOT NULL,
    CONSTRAINT fk_email_change_request_user
        FOREIGN KEY (user_id) REFERENCES users(id_user) ON DELETE CASCADE
)